# Travis CI (http://travis-ci.org/) is a continuous integration
# service for open source projects. This file configures it
# to run unit tests for docopt-go.

language: go

services:
  - docker
  
go:
  - tip

install:
  - make install

script:
  - make test

